# Generated by Django 5.0.8 on 2025-09-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos/')),
                ('duration_sec', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('error', 'error')], default='processing', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('embedding', models.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'start_sec'], name='videos_tran_video_i_39bf4b_idx')],
            },
        ),
    ]
